application/models.py
#! /usr/bin/python
# _*_ coding: utf-8 _*_
# Desc: define all models in all blueprint

from . import database
from . import login_manager

# define permissions
class Permission:
    PERMISSION_FOLLOW = 0x01
    PERMISSION_COMMENT = 0x02
    PERMISSION_ARTICLE = 0x04
    PERMISSION_MANAGE_COMMENT = 0x08
    PERMISSION_ADMIN = 0x80

# define Role model
class Role(database.Model):
    __tablename__='role'
    id=database.Column(database.Integer, primary_key=True)
    name=database.Column(database.String(32), unique=True)
    default=database.Column(database.Boolean, index=True)
    permission=database.Column(database.Integer)
    users=database.relationship('User', backref='role', lazy='dynamic')

    @staticmethod
    def insert_roles():
        roles = {
            'User':(Permission.PERMISSION_FOLLOW | 
                Permission.PERMISSION_COMMENT |
                Permission.PERMISSION_ARTICLE, True),
            'Moderator':(Permission.PERMISSION_FOLLOW |
                Permission.PERMISSION_COMMENT |
                Permission.PERMISSION_ARTICLE |
                Permission.PERMISSION_MANAGE_COMMENT, False),
            'Admin':(0xff, False)
        }
        for role_name in roles:
            role = Role.query.filter_by(name=role_name).first()
            if role is None:
                role = Role(name=role_name)
            role.permission = roles[role_name][0]
            role.default = roles[role_name][1]
            database.session.add(role)
        database.session.commit()

    def __repr__(self):
        return 'role <%s|%d>' % (self.name, self.permission)

# define User model
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import UserMixin, AnonymousUserMixin
from itsdangerous import TimedJSONWebSignatureSerializer as Serializer
from flask import current_app
class User(UserMixin, database.Model):
    __tablename__='user'
    id=database.Column(database.Integer, primary_key=True)
    name=database.Column(database.String(32), unique=True, index=True)
    email=database.Column(database.String(32), unique=True, index=True)
    password=database.Column(database.String(128))
    role_id=database.Column(database.Integer, database.ForeignKey('role.id'))
    confirmed=database.Column(database.Boolean, default=False)
    realname=database.Column(database.String(32))
    location=database.Column(database.String(64))
    aboutme=database.Column(database.Text())

    def __init__(self, **kwargs):
        super(User, self).__init__(**kwargs)
        if self.role is None:
            if self.email == current_app.config['FLASK_ADMIN']:
                self.role = Role.query.filter_by(permission=0xff).first()
            if self.role is None:
                self.role = Role.query.filter_by(default=True).first()

    def set_password(self, password):
        self.password = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.password, password)

    def generate_confirmation_token(self, expiration=3600):
        serial=Serializer(current_app.config['SECRET_KEY'], expiration)
        return serial.dumps({'confirm':self.id})

    def confirm(self, token):
        serial=Serializer(current_app.config['SECRET_KEY'])
        try:
            data=serial.loads(token)
        except:
            return False
        if data.get('confirm') != self.id:
            return False
        self.confirmed=True
        database.session.add(self)
        database.session.commit()
        return True

    # permission
    def can(self, permission):
        return self.role is not None and (self.role.permission & permission) == permission

    # admin
    def is_admin(self):
        return self.can(Permission.PERMISSION_ADMIN)

# anonymous user permission
class AnonymousUser(AnonymousUserMixin):
    def can(self, permission):
        return False

    def is_admin(self):
        return False

login_manager.anonymous_user = AnonymousUser

# callback function for login_manager to get login user
from . import login_manager
@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

application/main/forms.py
#! /usr/bin/python
# _*_ coding: utf-8 _*_
# Desc: define main blueprint forms

from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField, PasswordField
from wtforms.validators import Length, EqualTo

# define edit profile form
class EditProfileForm(FlaskForm):
    realname=StringField('Realname', validators=[Length(0, 64)])
    location=StringField('Location', validators=[Length(0, 64)])
    aboutme=TextAreaField('About Me')
    submit=SubmitField('Modify')

# define change password from
class ChangePasswordForm(FlaskForm):
    old_password=PasswordField('Old Password')
    new_password=PasswordField('New Password')
    confirm_password=PasswordField('Confirm Password', validators=[EqualTo('new_password')])
    submit=SubmitField('Modify')

application/__init__.py
#! /usr/bin/python
# _*_ coding: utf-8 _*_
# Desc: initilize and create application instance by factory mode

# add flask and render template support
from flask import Flask, render_template

# add bootstrap support
from flask_bootstrap import Bootstrap
bootstrap = Bootstrap()

# add moment support
from flask_moment import Moment
moment = Moment()

# add database support
from flask_sqlalchemy import SQLAlchemy
database = SQLAlchemy()

# add mail support
from flask_mail import Mail
mail = Mail()

# add login support
from flask_login import LoginManager
login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'

# add config
from config import config

# create application instance
def create_application(config_name):
    application = Flask(__name__)

    # init application by configuration
    application.config.from_object(config[config_name]())

    # init application by bootstrap
    bootstrap.init_app(application)

    # init application by moment
    moment.init_app(application)

    # init application by database
    database.init_app(application)

    # init application by mail
    mail.init_app(application)

    # inir application by login manager
    login_manager.init_app(application)

    # init application by other module

    # register main blueprint
    from .main import main as main_blueprint
    application.register_blueprint(main_blueprint)

    # register auth blueprint, and add url_prefix
    from .auth import auth as auth_blueprint
    application.register_blueprint(auth_blueprint, url_prefix='/auth')

    # return application instance
    return application

application/main/__init__.py
#! /usr/bin/python
# _*_ coding: utf-8 _*_
# Desc: module main initialize as blueprint

# define a blueprint main
from flask import Blueprint
main = Blueprint('main', __name__)
from . import views, errors

# register permission into context
from ..models import Permission
@main.app_context_processor
def register_permission():
    return dict(Permission=Permission)

application/main/views.py
#! /usr/bin/python
# _*_ coding: utf-8 _*_
# Desc: blueprint form views handlers

from flask import render_template, abort, redirect, url_for, flash
from ..models import User
from flask_login import current_user, login_required, logout_user
from .. import database
from .forms import EditProfileForm, ChangePasswordForm

# define route / views
from . import main
@main.route('/')
def index():
    return render_template('index.html')

# user info view
@main.route('/user/<username>')
def user(username):
    user = User.query.filter_by(name=username).first()
    if user is None:
        abort(404)
    return render_template('user.html', user=user)

# edit user profile view
@main.route('/user/edit-profile', methods=['GET', 'POST'])
@login_required
def edit_profile():
    form = EditProfileForm()
    if form.validate_on_submit():
        current_user.realname = form.realname.data
        current_user.location = form.location.data
        current_user.aboutme = form.aboutme.data
        database.session.add(current_user)
        database.session.commit()
        flash('Your profile has been updated.')
        return redirect(url_for('main.user', username=current_user.name))
    form.realname.data = current_user.realname
    form.location.data = current_user.location
    form.aboutme.data = current_user.aboutme
    return render_template('edit-profile.html', form=form)

# change password view
@main.route('/user/change-password', methods=['GET', 'POST'])
@login_required
def change_password():
    form=ChangePasswordForm()
    if form.validate_on_submit():
        if not current_user.check_password(form.old_password.data):
            flash('old password is invalid')
            return render_template('change-password.html', form=form)
        if form.old_password.data == form.new_password.data:
            flash('old password same as new password')
            return render_template('change-password.html', form=form)
        if form.new_password.data != form.confirm_password.data:
            flash('new password does not equal to comfirm password')
            return render_template('change-password.html', form=form)
        current_user.set_password(form.confirm_password.data)
        database.session.add(current_user)
        database.session.commit()
        flash('change password successfully, please login use new password')
        return redirect(url_for('auth.logout'))
    form.old_password.data = ''
    form.new_password.data = ''
    form.confirm_password.data = ''
    return render_template('change-password.html', form=form)

application/templates/base.html
{% extends "bootstrap/base.html" %}

{% block title %}Flask{% endblock %}

{% block head %}
{{ super() }}
<link rel="shortcut icon" href="{{url_for('static', filename='icon/favicon.ico')}}" type="image/x-icon">
<link rel="icon" href="{{url_for('static', filename='icon/favicon.ico')}}" type="image/x-icon">
{% endblock %}

{% block navbar %}
<div class="navbar navbar-inverse" role="navigation" style="border-radius:0px">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{{ url_for('main.index') }}">Python.Flask</a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href='#'>C/C++</a></li>
                <li><a href='#'>Java</a></li>
                <li><a href='#'>Python</a></li>
                <li><a href='#'>Oracle</a></li>
                <li><a href='#'>MySQL</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if current_user.is_authenticated %}
                <li class='dropdown'>
                    <a class='dropdown-toggle' data-toggle='dropdown' aria-haspopup='true' aria-expanded='false'>
                        {{ current_user.name}}
                        <span class='caret'></span>
                    </a>
                    <ul class='dropdown-menu' role='menu'>
                        <li role='presentation'>
                            <a role='menuitem' href='{{ url_for("main.change_password") }}'>ChangePassword</a>
                        </li>
                        <li role='presentation'>
                            <a role='menuitem' href='{{ url_for("main.user", username=current_user.name) }}'>Profile</a>
                        </li>
                        <li role='presentation'>
                            <a role='menuitem' href='{{ url_for("auth.logout") }}'>Logout</a>
                        </li>
                    </ul>
                </li>
                {% else %}
                <li><a href="{{ url_for('auth.login') }}">Login</a></li>
                <li><a href="{{ url_for('auth.register') }}">Register</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</div>
{% endblock %}

{% block content %}
<div class='container'>
    {% for message in get_flashed_messages() %}
    <div class='alert alert-warning'>
        <button type='button' class='close' data-dismiss='alert'>&times;</button>
        {{ message }}
    </div>
    {% endfor %}
    
    {% block page_content %}{% endblock %}
</div>
{% endblock %}

{% block scripts %}
{{ super() }}
{{ moment.include_moment() }}
{% endblock %}

application/templates/change-password.html
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block title %}Change Password{% endblock %}

{% block page_content %}
<div class='page-header'>
    <h1>Change Password</h1><br>
</div>
<div class='col-md-4'>
    {{ wtf.quick_form(form) }}
</div>
{% endblock %}

application/templates/edit-profile.html
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block title %}Edit User Profile{% endblock %}

{% block page_content %}
<div class='page-header'>
    <h1>Edit {{ current_user.name }} Profile</h1><br>
</div>
<div class='col-md-4'>
    {{ wtf.quick_form(form) }}
</div>
{% endblock %}

application/templates/index.html
{% extends "base.html" %}

{% block title %}Index{% endblock %}

{% block page_content %}
<h1>Hello, {% if current_user.is_authenticated %}{{ current_user.name}}{% else %}Stranger{% endif %}!</h1>
{% endblock %}

application/templates/user.html
{% extends "base.html" %}

{% block title %}User Information{% endblock %}

{% block page_content %}
<div class='page-header'>
    <h1>User {{ user.name }} Information</h1><br>
    <p>Username: {{ user.name }}</p>
    <p>E-mail  : {{ user.email }}</p>
    {% if user.realname %}
    <p>Realname: {{ user.realname }}
    {% endif %}
    {% if user.location %}
    <p>Location: {{ user.location }}
    {% endif %}
    {% if user.aboutme %}
    <p>Aboutme : {{ user.aboutme }}
    {% endif %}
    <br><br>
    {% if user.email == current_user.email  %}
        <p>Click <a href='{{ url_for("main.edit_profile") }}'>here</a> to modify profile.</p>
    {% endif %}
</div>
{% endblock %}